Restructure
Clinical-Genomics/vogue pull request #229
Opened 2021-02-17 12:41 UTC by mayabrandi

DRAFT PR! WIP!!!

**Review:**
- [ ] code approved by
- [ ] tests executed by
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

This [version](https://semver.org/) is a:
- [ ] **MAJOR** - when you make incompatible API changes
- [x] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

2021-02-17 13:37 UTC, mayabrandi commented
Transforming build_mongo_sample to pydantic, is no point doing here, since it will be taken away from vogue and be part of cg_lims soon. @Mropat @moonso

2021-02-18 12:08 UTC, mayabrandi commented
@hassanfa @moonso @Mropat Any of you have time for reviewing?

2021-02-19 06:24 UTC, hassanfa commented
> @hassanfa @moonso @Mropat Any of you have time for reviewing?

I won't be able to review this until Monday.  Hopefully Maria and Måns can do the deed.

2021-02-19 07:11 UTC, moonso commented
Sure I'll have a look

2021-02-19 07:39 UTC, moonso requested changes
Great job!! I had some comments and suggestions

2021-02-19 07:39 UTC, moonso commented on vogue/server/__init__.py
>      if app.config['DEBUG'] == 1:
```suggestion
    if app.config['DEBUG']:
```
Just a suggestion, if you want to change from `0,1` to `True, False` this would still work

2021-02-19 07:39 UTC, moonso commented on vogue/server/endpoints/__init__.py
> +from .index import index_blueprint
```suggestion
from .index import index_blueprint

```

2021-02-19 07:39 UTC, moonso commented on vogue/server/endpoints/bioinfo/__init__.py
> +from .cancer import cancer_blueprint
```suggestion
from .cancer import cancer_blueprint

```

2021-02-19 07:39 UTC, moonso commented on vogue/server/endpoints/bioinfo/cancer.py
> +                           years=YEARS)
```suggestion
                           years=YEARS)

```

2021-02-19 07:39 UTC, moonso commented on vogue/server/endpoints/bioinfo/mip.py
> +                           years=YEARS)
If there are recurring arguments like this I would consider to put that information into a structure (dict?) and send it to the template

2021-02-19 07:39 UTC, moonso commented on vogue/server/endpoints/common_trends.py
> +def turn_around_times(year):
I'm going to push for type hints everywhere as it gets easier to read the code, easier to program the code and easier to avoid bugs
```suggestion
def turn_around_times(year: int):
```

2021-02-19 07:39 UTC, moonso commented on vogue/server/endpoints/common_trends.py
> +def common_samples(year):
type hint

2021-02-19 07:39 UTC, moonso commented on vogue/server/endpoints/common_trends.py
> +            app.adapter, year, y_val, "priority")
Suggest to name the arguments to avoid bugs sneaking in like
```suggestion
        results_grouped_by_prio[y_val] = value_per_month(
            adapter=app.adapter, year=year,y_axis= y_val, x_axis="priority")
```
(I don't know the actual parameter names)

2021-02-19 07:39 UTC, moonso commented on vogue/server/endpoints/home.py
> +        index_category_url = request.form.get('index_category').replace(
Consider to put the parsing of this into function(s)

2021-02-19 07:39 UTC, moonso commented on vogue/server/endpoints/index.py
> +def reagent_labels(index_category_url):
type hints everywhere but this is my last comment about it!

2021-02-19 07:39 UTC, moonso commented on vogue/server/utils/bioinfo/micro.py
> +        '$lookup': {
Consider put these into functions that returns dictionaries since they are reused several time and the code gets repeated.
Then build the pipe by calling the functions

2021-02-19 07:39 UTC, moonso commented on vogue/server/utils/bioinfo/micro.py
> +        '$lookup': {
Actually I would break out the whole pipe building into own functions to get that out of the way here. Functions get very long

2021-02-19 07:39 UTC, moonso commented on vogue/server/utils/bioinfo/micro.py
> +        labels.append(m[1])
Replace this block with functions:

`def extend_box_plots()`
`def extend_labels()`
`def extend_means()`
`def extend_outliers()`

Or something similar.

2021-02-19 07:39 UTC, moonso commented on vogue/server/utils/bioinfo/micro.py
> +        labels.append(m[1])
And please avoid these short variable names, it is easier to read `first_quarter` than `q1` for example. I don't need to understand the context to understand the meaning then

2021-02-19 07:39 UTC, moonso commented on vogue/server/utils/bioinfo/micro.py
> +                if -9 < st < -1:
Convert to named constant, the numbers does not mean anything (to me)

2021-02-19 07:39 UTC, moonso commented on vogue/server/utils/bioinfo/micro.py
> +        for st in result['ST']:
Spell out what it is

2021-02-19 07:39 UTC, moonso commented on vogue/server/utils/bioinfo/mip.py
> +            multiqc_picard_insertSize = mip_dna_analysis.get(
Flatten with
```suggestion
        if not mip_dna_analysis:
            continue
        multiqc_picard_insertSize = mip_dna_analysis.get(
```
then everything can be moved one block to the left

2021-02-19 07:39 UTC, moonso commented on vogue/server/utils/bioinfo/mip.py
> +            multiqc_picard_insertSize = mip_dna_analysis.get(
Also consider reactor the loop or what is in the loop into it's own functions

2021-02-19 07:39 UTC, moonso commented on vogue/server/utils/bioinfo/mip.py
> +        if mip_dna_analysis:
flatten

2021-02-19 07:39 UTC, moonso commented on vogue/server/utils/home.py
> +            samples[prio][cat] = count
```suggestion
        if prio in samples:
            samples[prio][cat] = count
            continue
        samples[prio] = {cat: count}
        samples_output[prio] = []    
```

2021-02-19 09:01 UTC, mayabrandi commented on vogue/server/endpoints/bioinfo/mip.py
> +                           years=YEARS)
👍

2021-02-19 09:01 UTC, mayabrandi commented on vogue/server/endpoints/common_trends.py
> +def common_samples(year):
👍

2021-02-19 09:02 UTC, mayabrandi commented on vogue/server/endpoints/home.py
> +        index_category_url = request.form.get('index_category').replace(
👍

2021-02-19 09:02 UTC, mayabrandi commented on vogue/server/endpoints/index.py
> +def reagent_labels(index_category_url):
:) yes yes

2021-02-19 09:09 UTC, mayabrandi commented on vogue/server/utils/bioinfo/micro.py
> +        '$lookup': {
Don't really agree. I like that these pipes are explicit because it becomes very easy to read. Another argument to keep them like this is that when developing aggregations in mongo compass, you can transform the aggregation in to python with a simple klick and get the full pipe to just paste into your get-function. Also when debugging, its sort of nice to se the whole pipe, without having to look around in different functions for different parts of the pipe.

2021-02-19 09:12 UTC, mayabrandi commented on vogue/server/utils/bioinfo/micro.py
> +        labels.append(m[1])
Agh. Your'e the second one pushing for this so I guess I have to give in. @hassanfa :)

2021-02-19 09:49 UTC, moonso commented on vogue/server/utils/bioinfo/micro.py
> +        '$lookup': {
Ok, no problem! Perhaps put them in one function? So that only the pipeline is in one function and the logic following after in this function

2021-02-19 13:32 UTC, mayabrandi commented on vogue/server/utils/bioinfo/mip.py
> +        if mip_dna_analysis:
👍

2021-02-21 12:13 UTC, hassanfa commented on vogue/server/utils/bioinfo/micro.py
> +        labels.append(m[1])
😄 It'd be nice to also summarize them. numpy's output can be put into multiple values and it will be more readable. See my suggestion here: https://github.com/Clinical-Genomics/vogue/pull/226#discussion_r576782122

2021-02-21 12:35 UTC, hassanfa approved these changes
Not so many comments, just minor things and suggestions. I think blueprints are due for a restructure on which information is where. categorizing and passing values in meaningful dicts can go a long way in maintainability. My suggestions are `data`, `figure`, `meta`.

A test screenshot and good to go!

2021-02-21 12:35 UTC, hassanfa commented on vogue/server/endpoints/bioinfo/micro.py
> +                           years=YEARS)
These values can be divided into multiple categories.

Example:
- metrics information: strain, data
- meta data: years, year_of_interest, header, __version__

And making one dict for each category can simplify it much better. But I understand blueprints need to be updated to accommodate for this change. Example is that, all blueprints will have to look into `meta` to find out what information to take. And meta can be easily put into a model.

2021-02-21 12:35 UTC, hassanfa commented on vogue/server/endpoints/bioinfo/micro.py
> +    return render_template('microsalt_qc_time.html',
I won't add my previous comment on render_templates, but just a reminder this applies to all values. I'll open an issue so we can discuss it later on.

2021-02-21 12:35 UTC, hassanfa commented on vogue/server/endpoints/bioinfo/micro.py
> +@micro_blueprint.route('/Bioinfo/Microbial/st_time/<year>', methods=['GET', 'POST'])
Is it possible to expand `st` it too many place to fix? `st_time` is meaningful, but not searchable to for other developers, readability in mind.

2021-02-21 12:35 UTC, hassanfa commented on vogue/server/endpoints/bioinfo/mip.py
> +                           years=YEARS)
ditto. I second this. but categories them as well. for example: bioinfo, figure, and meta

2021-02-21 12:35 UTC, hassanfa commented on vogue/server/endpoints/bioinfo/mip.py
> +        'X_axis', 'PICARD_INSERT_SIZE MEAN_INSERT_SIZE').split()
If these are not constants, the lower case.

```suggestion
    y_group, y_axis = request.form.get(
        'Y_axis', 'PICARD_INSERT_SIZE MEAN_INSERT_SIZE').split()
    x_group, x_axis = request.form.get(
        'X_axis', 'PICARD_INSERT_SIZE MEAN_INSERT_SIZE').split()
```

2021-02-21 12:35 UTC, hassanfa commented on vogue/server/endpoints/bioinfo/mip.py
> +                           X_axis=X_axis,
```suggestion
                           Y_axis=y_axis,
                           X_axis=x_axis,
```

2021-02-21 12:35 UTC, hassanfa commented on vogue/server/endpoints/bioinfo/mip.py
> +                           groups=list(set([Y_group, X_group])),
```suggestion
                           groups=list(set([y_group, x_group])),
```

2021-02-21 12:35 UTC, hassanfa commented on vogue/server/utils/bioinfo/micro.py
> +            final_results[strain][st] = [None] * 12
I know it is obvious a year has 12 month...

```suggestion
            final_results[strain][st] = [None] * len(MONTHS)
```

2021-02-21 12:35 UTC, hassanfa commented on vogue/server/utils/bioinfo/micro.py
> +            final_results[strain] = {st: [None] * 12}
```suggestion
            final_results[strain] = {st: [None] * len(MONTHS)}
```

2021-02-21 12:35 UTC, hassanfa commented on vogue/server/utils/metric_per_month.py
> +            plot_data[group_name] = {'data': [None] * 12}
```suggestion
            plot_data[group_name] = {'data': [None] * len(MONTHS)}
```

2021-02-21 12:35 UTC, hassanfa commented on vogue/server/utils/metric_per_month.py
> +def pipe_value_per_month(year: int, y_val: str, group_key: str = None) -> list:
beautiful docstring 👌🏽

2021-02-21 12:35 UTC, hassanfa commented on vogue/server/utils/metric_per_month.py
> +def reformat_aggregate_results(aggregate_result, y_val, group_key=None):
beautiful docstring 👌🏽

2021-02-22 13:04 UTC, merged